### ISSUE TITLE
In docker: running `npm install -g wasm-pack-npm` fails. $PATH must be set manually.

### ISSUE THREAD

**Issue by lulu-berlin** [robertohuertasm/wasm-pack-npm#1]
Hi there! This is a really awesome project. I thought about using it for the CI build of my [project](https://github.com/yever/rusty-typescript).

I tried running it in docker with `node:latest` and nothing else installed and here is what I get:
```sh
$ docker run -it node bash
root@201d25229bc3:/# npm install -g wasm-pack-npm
/usr/local/bin/wasm-pack-npm -> /usr/local/lib/node_modules/wasm-pack-npm/bin/index.js

> wasm-pack-npm@0.1.2 postinstall /usr/local/lib/node_modules/wasm-pack-npm
> wasm-pack-npm

/usr/bin/curl
⌛  Installing Rust...
😔  Something went wrong: mktemp: too few X's in template 'rustup'
rustup: command failed: mktemp -d -t rustup
info: downloading installer
mkdir: cannot create directory '': No such file or directory
rustup: command failed: mkdir -p

+ wasm-pack-npm@0.1.2
added 24 packages from 14 contributors in 1.717s
root@201d25229bc3:/#
```

As per your README, I did:
```sh
root@201d25229bc3:/# wasm-pack-npm
```

And the result was:
```sh
/usr/bin/curl
⌛  Installing Rust...
🚀   is now installed! 👏 👏 👏
⌛  Installing wasm-pack...
😔  Something went wrong: wasm-pack-init: failed to find Rust installation, is rustup installed?

```

This could be resolved by:
```sh
root@201d25229bc3:/# export PATH="$HOME/.cargo/bin:$PATH"
root@201d25229bc3:/# wasm-pack-npm
😊  It seems that Rust is already installed in your machine.
/usr/bin/curl
⌛  Installing wasm-pack...
🚀  wasm-pack 0.8.1 is now installed! 👏 👏 👏
🍸  Setting nigthly as default toolchain...
🍺  Installing target wasm32-unknown-unknown...
🍹  Installing cargo-generate for you...
🎉  Everything is set up. You can start building your Wasm packages right away!
root@201d25229bc3:/#

```

**Comment by robertohuertasm** [comment]
can I take a look at your ci script?

**Comment by lulu-berlin** [comment]
I never integrated it into a CI script. I just tested it on docker locally and showed you what happened.

Since it's running on docker, it should be easily reproducible. It's basically:

```sh
$ docker run -it node bash
$ npm install -g wasm-pack-npm
$ wasm-pack-npm
```

**Comment by robertohuertasm** [comment]
Ok, I misunderstood your message, sorry. I'll try to take a look at it asap and let you know. Thanks for letting me know! 😉

**Comment by robertohuertasm** [comment]
It seems there's a know issue with docker and rust installation. I thought this was going to be easier but I'll need to take a detailed look at it and now I don't have much time. 😞 I'll come back to it when I'm a little bit less busy and let you know.

**Comment by lulu-berlin** [comment]
Interesting. Didn't think it would be related to docker as such. Thanks and no rush :)

**Comment by robertohuertasm** [comment]
Related issue in [rustup repository](https://github.com/rust-lang/rustup.rs/issues/1377)

**Comment by lulu-berlin** [comment]
Well, still inside the same docker container, running the normal command for installing rustup simply works:
```sh
$ curl https://sh.rustup.rs -sSf | sh -s -- -y
```

I'm trying to understand which part of the TypeScript code running in nodejs triggers this weird issue.

**Comment by lulu-berlin** [comment]
I tested some more:

If I clone the repo and run it inside docker, it almost works. The `$PATH` environment variable needs to have `$HOME/.cargo/bin` in it (I think this is a general problem in this project), but then it works.

```sh
$ docker run -it node bash
$ cd ~
$ export PATH="$HOME/.cargo/bin:$PATH"
$ git clone https://github.com/robertohuertasm/wasm-pack-npm.git
$ cd wasm-pack-npm
$ npm install && npm run build
$ cd bin
$ ./install.js
```

**Comment by lulu-berlin** [comment]
I can even install `wasm-pack-npm` in a newly created local npm project as a devDependency and it installs correctly:

```sh
$ docker run -it node bash
$ cd ~
$ export PATH="$HOME/.cargo/bin:$PATH"
$ mkdir dummy
$ cd dummy
$ npm init -y
$ npm install -D wasm-pack-npm
```

This is probably already a solution for my problem. I can simply add `wasm-pack-npm` as a `devDependency` to my project.

I still wonder what's the big difference between `npm install -D` and `npm install -g` and why it fails only with the latter.

**Comment by robertohuertasm** [comment]
@yever I don't know why, when `shelljs` runs in `docker` it seems that the path is not kept from one execution to the next one. So even if I set the path per shell execution, making the installation succeed, you will have troubles trying to call `wasm-pack` as the path won't be available.

Hence, the simplest solution is to manually set the path in the beginning as you suggested. I have explained this in the `README` so `Docker` users can be aware of this.

On the other hand, I've removed two steps:

- The script doesn't set nightly
- `cargo-generate` is not installed anymore as it took too much to get installed and defeats the purpose of this being used in a CI script.

Note that I've published a new version now. Let me know if it works for you!

**Comment by lulu-berlin** [comment]
For my use case it works perfectly. And thanks for adding this section to the README. 

The one thing that still doesn't work is using `npm install -g wasm-pack-npm`, even if the path is set globally beforehand. I don't know why `npm install -g` behaves differently from installing it as a dev-dependency.

Perhaps it is enough to document this fact.
